services:
  three-in-line:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: react-playground
    volumes:
      - ./projects:/projects
    ports:
      - '3001:3000'
    stdin_open: true
    tty: true
