# Usar una imagen base de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /projects

# Copiar los archivos de package.json y package-lock.json
# COPY package*.json ./

# Instalar las dependencias
# RUN npm install -g vite
# RUN yarn add -D vite

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando por defecto (no ejecuta nada, solo abre una terminal)
CMD ["sh"]